### ISSUE TITLE
TriChorus Popcorn

### ISSUE THREAD

**Issue by mhuss99** [clevelandmusicco/HothouseExamples#11] opened 2024-09-29 03:34 UTC
I'm new to Daisy and Hothouse - I just built my HH kit, and built and flashed the TriChorus example/project. It sounds great, but when it passing signal it's making subtle popping noises, random and relatively slow like the ticks when playing an LP record. Has anyone else seen (heard) this problem? I didn't notice it at first when testing though a (mono) guitar amp, but when connected to a DAW in stereo the noise is obvious and annoying.

**Comment by clevelandmusicco** [comment] 2024-09-29 07:19
What you're describing may be USB noise. If you unplug the USB cable from your computer, does the noise stop?

**Comment by mhuss99** [comment] 2024-09-30 15:51
No, it was just running on a standard 9v 1.7A pedal supply. The only connection to the computer was via a Motu external audio interface.

**Comment by clevelandmusicco** [comment] 2024-09-30 17:26
Hmm. I've tried on multiple systems now, and I cannot reproduce this.

One thing does come to mind, though: do a `git pull` to make sure you're using the latest code. In [this commit](https://github.com/clevelandmusicco/HothouseExamples/commit/8aba42aa6d8b133fb3c22d0acf2dd79f67a9a00e) from less than a week ago, the output for the TriChorus was changed from mono to stereo. If you're running the old mono code, the right channel would be "floating" and have no assigned output. That could cause some noise in some cases.

**Comment by mhuss99** [comment] 2024-09-30 20:47
That seems to have fixed it, thanks. 

Aside: Sadly, my audio interface seems to switch to line mode when I plug in a stereo cable, so I have to crank the gain way up and it gets noisy.

**Comment by clevelandmusicco** [comment] 2024-09-30 21:52
OK, good to know your popcorn issue is fixed. Keep in mind when writing your own effects that if you're writing it specifically for mono, you should write zeroes to the right output in case someone tries to run it in stereo. This is why you didn't have an issue listening to the left channel in your amp, but then heard it when you plugged in the right channel to your interface. 

Re: the need to crank the gain on your interface, something seems amiss. I use a MOTU UltraLite mk5 and when the Hothouse output is plugged into its line level 7-8 inputs, I don't have to touch the gain at all with a humbucker guitar. With the gain at 0dB, the signal averages around -18 on the meters, which is an ideal recording level. For single coils, I might bump up the gain by about 6-8dB to get the same level. In neither case is it noisy.

Just to be sure, the [TriChorus example uses KNOB 1 as a master volume control](https://github.com/clevelandmusicco/HothouseExamples/tree/main/src/TriChorus). You have that turned up and you still have to crank the interface's gain?

**Comment by mhuss99** [comment] 2024-10-01 01:38
Thanks for that feedback - that might be a good comment to add to the source. somewhere.

RE: gain, Yep, it's really quiet even when bypassed, not the pedal. I'm using the front panel combo jack (ch1).

**Comment by clevelandmusicco** [comment] 2024-10-01 10:00
> Thanks for that feedback - that might be a good comment to add to the source. somewhere.

Good idea. I'll add it to the "Creating your own effects" wiki content I am working on. Ultimately, the user can program the device any way they wish for any use case they can imagine. The examples are just that, but this is one such use case that the examples (or doc) could demonstrate more clearly.

> it's really quiet even when bypassed, not the pedal

The Hothouse is digital and does not have a mechanical bypass. So, "bypass" simply means the input audio is being passed to the output. It still goes through the ADC and DAC of the Daisy Seed. Consider the TriChorus code:

```cpp
// mono-to-stereo
out[0][i] = bypass ? in[0][i] : (sig_l * wet + in[0][i] * (1.0f - wet)) * vol;
out[1][i] = bypass ? in[0][i] : (sig_r * wet + in[0][i] * (1.0f - wet)) * vol;
```

When bypassed, samples from `in[]` are fed directly to `out[]` at unity gain. The analog audio I/O buffers in the Hothouse itself are also fixed at unity gain.

> I'm using the front panel combo jack (ch1).

Gotcha. I only mentioned "line level 7-8 inputs" to say that driving a line level input is not a problem. The front panel "mic/line/instr" inputs don't present any noise or level issues either.

Since the original issue here (the popcorn sound) is resolved, I'm going to close this thread. But if you can't sort out your setup's noise or signal level issues, feel free to let us know!

**Closed by clevelandmusicco** 2024-10-01 10:00 UTC
